# Generated by Django 3.2.22 on 2023-11-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_rgq6aq.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_filter',
            field=models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('python', 'Python'), ('react', 'React')], default='html', max_length=32),
        ),
    ]
