# Generated by Django 3.2.22 on 2023-11-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20231103_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_filter',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('React', 'React')], default='HTML', max_length=32),
        ),
    ]
